# Generated by Django 4.2.1 on 2023-05-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Дорога', max_length=150, verbose_name='Название')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page', verbose_name='Страница')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subroad', to='road.road', verbose_name='Дорога, от которой пошла развилка')),
            ],
            options={
                'verbose_name': 'Дорога',
                'verbose_name_plural': 'Дороги',
            },
        ),
    ]
