# Generated by Django 4.2.1 on 2023-05-28 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('road', '0001_initial'),
        ('page', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='road',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='road',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subroad', to='road.road', verbose_name='Дорога, от которой пошла развилка'),
        ),
    ]
