# Generated by Django 4.2.1 on 2023-07-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('road', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст блока')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='BlocksOnRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс блока в дороге')),
                ('original_road', models.BooleanField(default=False, verbose_name='Оригинальный блок дороги')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.block')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='roads',
            field=models.ManyToManyField(through='block.BlocksOnRoad', to='road.road', verbose_name='Дороги'),
        ),
    ]
