# Generated by Django 4.2.1 on 2023-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=False, verbose_name='Начальный блок дороги')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст блока')),
                ('next_blocks', models.ManyToManyField(blank=True, to='block.block', verbose_name='Следующий(-е) блок(-и)')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
    ]
