# Generated by Django 4.2.1 on 2023-05-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0001_initial'),
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road', verbose_name='Дорога'),
        ),
    ]
