# Generated by Django 4.2.1 on 2023-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс в списке подстраниц'),
        ),
    ]
