# Generated by Django 4.2.1 on 2023-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='floor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Индекс в списке подстраниц'),
        ),
    ]
